package com.joma.studies;

import org.apache.log4j.BasicConfigurator;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        BasicConfigurator.configure();

        System.out.println(new App().getGreeting());
    }
}
