package com.joma.studies;

import com.beust.jcommander.JCommander;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.joma.studies.article.lucile.IndexArticleListener;
import com.joma.studies.article.xml.XmlReader;
import org.apache.log4j.Logger;

import java.io.File;
import java.io.FileInputStream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static final Logger logger = Logger.getLogger(App.class);


    public static void main(String[] args) {
        try {
            ConfigProvider configProvider = getConfig(args);

            Injector injector = Guice.createInjector(new AppModule(configProvider));

            XmlReader xmlReader = injector.getInstance(XmlReader.class);
            IndexArticleListener indexArticleListener = injector.getInstance(IndexArticleListener.class);

            xmlReader.addObserver(indexArticleListener);
            xmlReader.read(new FileInputStream(
                    new File(configProvider.getInputXmlPath())
            ));

            indexArticleListener.finish();

            logger.info("Import ended with success");
        } catch (Exception e) {
            logger.fatal(e.getMessage());
        }
    }

    private static ConfigProvider getConfig(String[] args) {
        ConfigProvider configProvider = new ConfigProvider();
        JCommander jCommander = new JCommander(configProvider);
        jCommander.setProgramName(App.class.getSimpleName());
        try {
            jCommander.parse(args);
            if (configProvider.isHelp()){
                jCommander.usage();
                System.exit(0);
            }
            return configProvider;
        }
        catch (Exception exception){
            jCommander.usage();
            throw exception;
        }
    }
}
